### ISSUE TITLE
Provide globally convergent scalar Newton method

### ISSUE THREAD

**Issue by mobius-eng** [PolyMathOrg/PolyMath#1]
Current Newton's method fails on `atan x = 0` if started far from `x = 0`, e.g `x = 5`.

Add line search to enhance the convergence.

Slice available here: http://smalltalkhub.com/#!/~PolyMath/PolyMathInbox/versions/SLICE-Issue-1-Globally-convergent-Newton-method-MobiusEng.1

**Comment by SergeStinckwich** [comment]
Added in v0.55
