### ISSUE TITLE
Fix CI for windows & Pharo 6.1

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/PolyMath#100]
CI for Windows is green for Pharo 7.0 and red for 6.1: https://ci.appveyor.com/project/SergeStinckwich/polymath-88bea/builds/24063518

**Comment by hemalvarambhia** [comment]
We've reemoved 6.1 for now from the build as this may be an issue in smalltalkCI. I will close it. We can open a new issue to re-introduce a 6.1 build.
