### ISSUE TITLE
Some tests methods fail randomly

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/PolyMath#104]
Some tests methods like :
- ``PMKolmogorovSmirnov1SampleTest >> testRejectOfEqualityHypothesesForSampleVersusDistribution``
- ``PMBinomialGeneratorTest >> testBinomialGeneratorConvergesToMean``
fail randomly from time to time. 

They should be rewritten in a better way.
Maybe we should control the seed in order to have reproducible test.

**Comment by hemalvarambhia** [comment]
This is a duplicate of #70, so I'll close that and this will be the new milestone issue.

**Comment by hemalvarambhia** [comment]
I'm proposing we do something like `Random seed: 0` as it's probably as good as any.

**Comment by hemalvarambhia** [comment]
@SergeStinckwich In the case of the K-S test work in PR #111 one observation I made is that the one talks about about retaining or rejecting the *null hypothesis*, whereas the message `rejectEqualityHypothesisWithAlpha` doesn't use that language. This is also the case in [wikipedia](https://en.wikipedia.org/wiki/Kolmogorov%E2%80%93Smirnov_test). So I was going to propose that we deprecate that in favour of `retainNullHypothesisWithin:` in a future version. What are your thoughts?
