### ISSUE TITLE
Math-Random package is messy

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/PolyMath#105]
The ``Math-Random`` is really messy and need to be cleaned :
- Some classes are subclasses of Random class
- some other classes are ``PMNumberGenerator``, some other from ``PMRandomGenerator``.
- What is the difference between ``PMNumberGenerator`` and ``PMRandomGenerator`` ?
- why some classes end with ``Generator`` other with ``RandomGenerator``, others by ``Kernel`` ?
- ``PMMarsagliaKissRandomKernel``is a subclass of ``Object`` and there is another class with almost the same name: ``PMMarsagliaKissRandom``. Maybe is their relationship ?

``PMLaplaceGenerator`` subclasses Object instead of ``PMRandomGenerator`` ...

**Comment by hemalvarambhia** [comment]
@SergeStinckwich With reference to point 3 (What is the difference between `PMNumberGenerator` and `PMRandomGenerator` ?) The `PMNumberGenerator` is dependent upon `PMRandomGenerator`. Every subclass has a `defaultGeneratorClass` class method who default is a subclass of `PMRandomGenerator` (Parker-Miller's algorithm). I think the class `PMRandomGenerator` should be called PMRandomNumberGeneratingAlgorithm, maybe. I will try and read up a little on the subject before renaming, though.

**Comment by hemalvarambhia** [comment]
On point 5, the class comment and [Wikipedia](https://en.wikipedia.org/wiki/KISS_(algorithm)) say that `PMMarsagliaKissRandom` is a PRNG. On the relationship question, `PMMarsagliaKissRandom` dependency on the kernel.

**Comment by hemalvarambhia** [comment]
So far, having reviewed the production code in Math-Random, the Mersenne Twister class's `nextInteger` message is quite long, a little difficult to understand. As a start we could try to extract some of the blocks to intention-revealing methods. I've found the original paper on the Mersenne Twister algorithm so this could be used for inspiration.

**Comment by hemalvarambhia** [comment]
The scope of the issue is potentially very large. I propose we break the issue up into smaller ones. I'll review the code and create issues accordingly.
