### ISSUE TITLE
Math-TSNE is incomplete

### ISSUE THREAD

**Issue by AtharvaKhare** [PolyMathOrg/PolyMath#115]
`tsneObj start` currently does nothing as:
- `runPCAonX` is commented out
- `x2p` is incomplete (Calculation of P-values)
- Core algorithm's iterations are incomplete

**Comment by SergeStinckwich** [comment]
Yes you are right, you code is not finish. Please contribute if you have time.

**Comment by AtharvaKhare** [comment]
Will give it a try today.

**Comment by SergeStinckwich** [comment]
Great but this is not an easy task. Having a working PCA implementation was the first step :-)

**Comment by AtharvaKhare** [comment]
`PMPrincipalComponentAnalyserJacobiTransformation` is currently working, whereas `PMPrincipalComponentAnalyserSVD` is not. Both have close-to-same outputs right?

If yes, then I'll use it for now.

**Comment by SergeStinckwich** [comment]
There is an ongoing work to implement t-SNE here: https://github.com/PolyMathOrg/PolyMath/projects

**Comment by AtharvaKhare** [comment]
I think there still is room for improvement in speed of t-SNE. One way would be using threads while computing joint probabilities. But main thing to do is profiling and checking for which parts are actually causing the slowdown.

**Comment by SergeStinckwich** [comment]
I don't see why threads will speedup the process. Yes profiling will help you identify the main slowdown.

**Comment by AtharvaKhare** [comment]
`computePairwiseAffinities` does binary search for every row of input - which is a big chunk of time for rows more than 1,000. I think splitting this loop into 4 or 8 threads will make it faster:
https://github.com/PolyMathOrg/PolyMath/blob/aaad4b29501b6a56d7a81a9dab8cba73221521ab/src/Math-TSNE/PMTSNE.class.st#L187-L239
since every row is independent of other.

**Comment by SergeStinckwich** [comment]
What do you mean by threads ? green threads in the Smalltalk VM ?

**Comment by AtharvaKhare** [comment]
I did not know that. So if Pharo is sequential, threads will not help.

**Comment by SergeStinckwich** [comment]
Pharo is not sequential, but process are green threads all running on the same VM thread.
