### ISSUE TITLE
Different Behavior for + and - with PMVector

### ISSUE THREAD

**Issue by nikhilpinnaparaju** [PolyMathOrg/PolyMath#120]
The following snippet works,
``` Smalltalk
| vect test |
vect := #(1 2 10) asPMVector .
test := vect + (-1 * vect max)
```

whereas,
``` Smalltalk
| vect test |
vect := #(1 2 10) asPMVector .
test := vect - vect max
```
does not.

**Comment by SergeStinckwich** [comment]
``PMVector>>+`` implementation is very different from ``PMVector>>-``.
I don't know why.

**Comment by nikhilpinnaparaju** [comment]
Exactly, ``PMVector>>+`` and ``PMVector>>*`` have a similar implementation but ``PMVector>>-`` is implemented differently.

Yes, I'll add tests for these.

**Comment by SergeStinckwich** [comment]
Apparently this works: 

```Smalltalk
- aVectorOrNumber
	"Answers the difference of the receiver with aVector."

	^ aVectorOrNumber negated addWithVector: self
```

**Comment by SergeStinckwich** [comment]
Yes add tests with difference with numbers and vectors.

**Comment by nikhilpinnaparaju** [comment]
Tests written and gave a suggested fix for the issue. PR submitted for review.
