### ISSUE TITLE
PMStandardScaler fails when scale = 0

### ISSUE THREAD

**Issue by AtharvaKhare** [PolyMathOrg/PolyMath#124]
A relevant example:
```Smalltalk
x := PMMatrix rows: #(#(1 0) #(1 0) #(1 1) #(1 1)).
scaler := PMStandardizationScaler new.
scaler fit: x.
scaler scale. "0"
scaler transform: x. "ZeroDivideError"
```

Possible fix: add a "handleZeroScale" method which changes scale to 1 when it is 0.
Question: Can this be method be added in `PMDataTransformer`? If we add more scalers in future, all would need this message.

**Comment by SergeStinckwich** [comment]
Why we should modify the scale to 1 when this is 0 :-)

**Comment by SergeStinckwich** [comment]
we should have a look how this is done in scikit-learn : https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

**Comment by AtharvaKhare** [comment]
We are doing `(element - mean) / scale`. When `scale=0`, we can't divide by zero. Since all elements are same, the `element-mean` will be 0 as it should be. So any number in the denominator will be fine. `1` specifically because any number divided by it is itself, but again, any number should be ok.

sklearn is also setting scale to 1.

**Comment by SergeStinckwich** [comment]
ok great if they use the same trick.

**Comment by SergeStinckwich** [comment]
Can you propose a fix, should be easy ?

**Comment by AtharvaKhare** [comment]
One of the fix is to modify this method: https://github.com/PolyMathOrg/PolyMath/blob/aaad4b29501b6a56d7a81a9dab8cba73221521ab/src/Math-PrincipalComponentAnalysis/PMStandardizationScaler.class.st#L24-L26
To calculate sqrt for every element, compare to 0, and return sqrt or 1.

Other way is to add a `handleZeros` method, but I do not think we should go there unless we add more types of scaling.

Do you want me to create PR using first suggested fix?

**Comment by SergeStinckwich** [comment]
Maybe later will have multiple type of scalin, but at the moment, we have only one.
So keep it simple and use first method. Maybe add a test when scale is 0 that it returns 1.
