### ISSUE TITLE
PMVector sum is extremely slow

### ISSUE THREAD

**Issue by AtharvaKhare** [PolyMathOrg/PolyMath#125]
Here is the comparison with array:
```Smalltalk
a := ((1 to: 5000) collect: [ :i | i ]) asPMVector.
a sum. "Best of 10 runs: 568ms"

b := ((1 to: 25000000) collect: [ :i | i ]).
b sum. "Worst of 10 runs: 551ms"
```

This means that `PMVector sum` is **at least 5,000 times slower** than `Collection sum`.

Possible fix: Don't override `sum` method. Is there any specific reason to do so?

**Comment by SergeStinckwich** [comment]
I try too remove ``PMVector>>sum``and it run much faster. The tests are all green.
I think we can remove it.
