### ISSUE TITLE
Eigenvalues/vectors in PolyMath

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/PolyMath#15]
There are 2 classes for supporting eigenvalues/eigenvectors at the moment: ```DhbJacobiTransformation``` and ```DhbLargestEigenValueFinder```.

These classes are not documented and no examples are provided.

Some examples are here :
- http://www.programcreek.com/python/example/7899/numpy.linalg.eig
- https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
- http://setosa.io/ev/eigenvectors-and-eigenvalues/

**Comment by SergeStinckwich** [comment]
In fact, one example is available in the comment of DhbJacobiTransformation:

```Smalltalk
| m jacobi eigenvalues eigenvectors |
m := DhbSymmetricMatrix rows: #((84 -79 58 55)
                                 (-79 84 -55 -58)
                                 (58 -55 84 79)
                                 (55 -58 79 84)).
jacobi := DhbJacobiTransformation matrix: m.
eigenvalues := jacobi evaluate.
eigenvectors := jacobi transform columnsCollect: [ :each | each].
```

**Comment by ShyshkinOleh** [comment]
How can I assign this task?

**Comment by SergeStinckwich** [comment]
You want to assign this task to who ?

**Comment by ShyshkinOleh** [comment]
To me)
I can not find any button or smth like this. I don't use git often, so probably I just missed something.

**Comment by SergeStinckwich** [comment]
Because you are not of the PolyMath org. I add you

**Comment by Uko** [comment]
Hey guys, how is the work going on? I've heard that @ShyshkinOleh implemented the SVD decomposition. Is it integrated? Is something missing?

**Comment by SergeStinckwich** [comment]
Normally this is integrated except the tests ...

**Comment by Uko** [comment]
@ShyshkinOleh, can you push tests so this task will be closed before Easter?

**Comment by SergeStinckwich** [comment]
I try to extract the tests but actually quite difficult to see the diff on metacello when you rename classes ...

**Comment by ShyshkinOleh** [comment]
@SergeStinckwich @Uko 
Currently, I have one test, which I showed to Yura, I'll push it soon and will write in Slack about it. I don't know if I can do more tests because, in general, we need to compare the final result, else should track by tests of methods I use.

**Comment by nicolas-cellier-aka-nice** [comment]
Hi,
Maybe you can create your test cases with things like P*D*inv(P) where D is
a diagonal matrix (eventually with 2x2 blocs if you're willing to test
cases with complex eigenvalues) and P is (pseudo-)randomly generated.

We can arrange to have P represented with exact fractions, and inv being
computed exactly too, as well as *, so to avoid problems related to
multiple rounding.

Or you could try to bench against well known linear algebra package test
sets.

2017-04-11 21:13 GMT+02:00 ShyshkinOleh <notifications@github.com>:

**Comment by SergeStinckwich** [comment]
Having more benchmarks will be nice for sure.

**Comment by ShyshkinOleh** [comment]
I added a test. Sorry for the delay, I had trouble with a system (reinstalling).
