### ISSUE TITLE
Load conflicts with current XMLParser if installed independently

### ISSUE THREAD

**Issue by hernanmd** [PolyMathOrg/PolyMath#169]
The current spec dependency to XMLWriter in the BaselineOfPolyMath references to 2.9.0:

```smalltalk
...
baseline: 'XMLWriter'
with: [ spec repository: 'github://pharo-contributions/XML-XMLWriter:2.9.0/src' ].
```

However XMLParser is loading XML-XMLWriter:2.9.x as this:

```smalltalk
spec
  baseline: 'XMLWriter'
  with: [ 
    spec
      loads: #('Core');
      repository: 'github://pharo-contributions/XML-XMLWriter:2.9.x/src' ]. 
```

This is causing conflict my [build of BioSmalltalk](https://travis-ci.org/hernanmd/BioSmalltalk/jobs/648128147) (and I suppose it could cause a similar error with any project loading PolyMath and XMLParser independently):

> MetacelloConflictingProjectError: Load Conflict between existing BaselineOfXMLWriter [baseline] from github://pharo-contributions/XML-XMLWriter:2.9.0/src and BaselineOfXMLWriter [baseline] from github://pharo-contributions/XML-XMLWriter:2.9.x/src

Is there any particular reason to use 2.9.0 and not 2.9.x ?

**Comment by SergeStinckwich** [comment]
Not sure to remember why we have a dependency to XMLWriter in PolyMath.

**Comment by hernanmd** [comment]
I've detected only two methods using XMLWriter now, both of them have no senders:

PMODEAccuracy>>runToXML
PMODEBenchmark>>runAllToXML:
(this last one is writing a Smark tag)

I would write a test (some context here would help) and if it passes, change BaselineOf from XML-XMLWriter:2.9.0 to XML-XMLWriter:2.9.x and run tests again.
