### ISSUE TITLE
Include Math-Matrix in a Metacello group

### ISSUE THREAD

**Issue by hernanmd** [PolyMathOrg/PolyMath#181]
In the current BaselineOf implementation **Math-Matrix** package is only included through the **Tests** group, so any external project which depends only of Math-Matrix functionality it is forced to load the PolyMath default group, or any other group which incidentally includes Matrix-Core.

This issue is made to add Math-Matrix to the Core group.

**Comment by hernanmd** [comment]
Issue is invalid. Matrix is loaded through another core package.

**Comment by SergeStinckwich** [comment]
Thank you Hernan, actually we need to redesign the dependencies in order to be able to load some part of PolyMath.
