### ISSUE TITLE
Try to replicate Numpy examples

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/PolyMath#19]
Try to reproduce NumPy examples like the one found here:

https://docs.scipy.org/doc/numpy/user/quickstart.html
or 
https://github.com/jakevdp/PythonDataScienceHandbook

Commit examples in PolyMath repository. If functions are missing, implement them.

**Comment by SergeStinckwich** [comment]
Any updates on this issue ?

**Comment by KupynOrest** [comment]
Yes, I am working on this, sorry for the late answer, I got plenty of deadlines previous week

**Comment by KupynOrest** [comment]
@SergeStinckwich At the moment I am reading Numerical Methods Book and working with matrices, I've recreated few simple examples from NumPy and I have some questions

- For example, I do not see an implementation of elementwise matrix product, I can add a method plus a Matlab-style operator (A  .* B). Would it be ok? 

- The next questions is in what format can I commit the examples and changes to PolyMath lib? Should I create a separate branch in this repository?

Thanks.

**Comment by SergeStinckwich** [comment]
- If you don't see any implementation, you can implement it. Please implement unit tests also
- You can push your changes, modifications, examples etc to main branches of PolyMath. We have an inbox for that: http://smalltalkhub.com/#!/~PolyMath/PolyMathInbox
- yes if there is no implementation

**Comment by KupynOrest** [comment]
@SergeStinckwich Hello, I have some examples and methods to push but I can not see anything at the link you sent in a previous message ( http://smalltalkhub.com/#!/~PolyMath/PolyMathInbox ). Maybe there is a problem with an access?

**Comment by SergeStinckwich** [comment]
The link is correct, but github replace ~ with something else. Check the link !

**Comment by SergeStinckwich** [comment]
github transform the URL with ~ inside ... please check the link

**Comment by KupynOrest** [comment]
Hello, I've implemented a number of different functions, here is a small set of examples. Let me know please if it is okay.
[Polymath.pdf](https://github.com/PolyMathOrg/PolyMath/files/767454/Polymath.pdf)

**Comment by SergeStinckwich** [comment]
Don't put pdf here. Better to just copy-paste your example here.

**Comment by KupynOrest** [comment]
|a b c d|
«This is how we can create a matrix, a and b are 2x3 matrices in
this example»
>> a := DhbMatrix rows: #( ( 1 0 1 ) (-1 -2 3)).
>> b := DhbMatrix rows: #( ( 1 2 3 ) (-2 1 7)).

«Matrix product»
>> c := a * b.

«Elementwise matrix product»
>> d := a dot:b.

«This is how we can create a vector»
>> a := #(1 4 9 16 25) asDhbVector.

«Vectors and Matrices support basic logical and arithmetic
operations»
>> Float pi sin * d.
>> a sqrt.
>> a > 3.
>> c cos.
>> c < 0.

«It is possible to create a vector/matrix of random numbers»
>> a := DhbVector randomSize: 10 maxNumber: 3.
>> b := DhbMatrix rows: 2 columns: 3 random: 5.

«It is also easy to create a vector/matrix of zeros/ones»
>> a := DhbVector ones:15.
>> b := DhbMatrix zerosRows: 2 cols: 3.

«We can also compute the cumulative sum or regular sum the vector/
matrix as following»
>> a := DhbMatrix rows: #( ( 1 0 1 ) (-1 -2 3)).
>> a cumsum.
//"a DhbVector(1 1 2)
//a DhbVector(-1 -3 0)»
>> a sum.
//»a DhbVector(2 0)»

«Matrix trace (sum of a diagonal elements for a square matrix)»
>> a := DhbMatrix rows: #((1 2 3)(4 5 6)(7 8 9)).
>> a trace.
// 15

**Comment by SergeStinckwich** [comment]
I refactor DHBXXX classes names to PMXXX in last version of PolyMath (v0.78).
Can you modified your example accordingly ? Thank you.

**Comment by KupynOrest** [comment]
Completely forgot to update my examples, sorry for that, here is the latest version

```smalltalk
|a b c d|
"This is how we can create a matrix, a and b are 2x3 matrices in
this example"
a := PMMatrix rows: #( ( 1 0 1 ) (-1 -2 3)).
b := PMMatrix rows: #( ( 1 2 3 ) (-2 1 7)).

"Matrix product"
c := a * b.

"Elementwise matrix product"
d := a dot:b.

"This is how we can create a vector"
a := #(1 4 9 16 25) asPMVector.

"Vectors and Matrices support basic logical and arithmetic
operations"
Float pi sin * d.
a sqrt.
a > 3.
c cos.
c < 0.

"It is possible to create a vector/matrix of random numbers"
a := PMVector randomSize: 10 maxNumber: 3.
b := PMMatrix rows: 2 columns: 3 random: 5.

"It is also easy to create a vector/matrix of zeros/ones"
a := PMVector ones:15.
b := PMbMatrix zerosRows: 2 cols: 3.

"We can also compute the cumulative sum or regular sum the vector/
matrix as following"
a := PMMatrix rows: #( ( 1 0 1 ) (-1 -2 3)).
a cumsum.
"a PMVector(1 1 2)"
"a PMVector(-1 -3 0)"
a sum.
"a PMVector(2 0)"

"Matrix trace (sum of a diagonal elements for a square matrix)"
a := PMMatrix rows: #((1 2 3)(4 5 6)(7 8 9)).
a trace.
"15"
```

**Comment by SergeStinckwich** [comment]
Code and examples commited in PolyMath v0.82
