### ISSUE TITLE
cholesky decomposition fails for certain cases

### ISSUE THREAD

**Issue by rakki-18** [PolyMathOrg/PolyMath#207]
I was trying to benchmark the Cholesky decomposition method and noticed that the method gives error for certain matrices.
Script to reproduce the error:
```Smalltalk
	|aPMMatrix expected|
	aPMMatrix := PMMatrix rows: #( #(4 20 8 2 18) #(20 116 80 18 126) #(8 80 117 32 135) #(2 18 32 73 109) #(18 126 135 109 272)).
        expected := PMMatrix rows: #( #(2 10 4 1 9) #(0 4 10 2 9) #(0 0 1 8 9) #(0 0 0 2 5) #(0 0 0 0 2)).
 
	aPMMatrix = (expected transpose * expected). "true"
        aPMMatrix choleskyDecomposition 
```
Calculating Cholesky decomposition for the above `aPMMatrix` gives the error, `sqrt undefined for number less than zero`.

```Smalltalk
diagonalValue := ((self at: j at: j) - rowSum) sqrt.
```
This line in the Cholesky decomposition method is causing the error where it is trying to calculate the square root of a negative number.

**Comment by rakki-18** [comment]
@olekscode can you please take a look?

**Comment by olekscode** [comment]
Hi, I am a bit busy today but I can take a look at it tomorrow evening or the day after tomorrow.

Does your matrix satisfy the conditions for Cholesky decomposition? It should be a Hermitian positive-drfinite matrix

**Comment by rakki-18** [comment]
@olekscode Hello, yes it satisfies the condition of being hermitian positive-definite matrix.
I have also provided the expected matrix in the script.
I also checked that `expected transpose * expected` evaluates to the initial matrix.
