### ISSUE TITLE
All the tests classes should be labelled correctly

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/PolyMath#21]
All tests classes should be inside packages labelled as Math-Tests-XXX

**Comment by SergeStinckwich** [comment]
The class ``PMLaplaceGeneratorTest``is in ``Math-RandomDistributionBased``, 2 tests classes are in ``Math-PrincipalComponentAnalysis`` and one class in ``Math-Number-Extensions``

**Comment by hemalvarambhia** [comment]
@SergeStinckwich Are you still working on this? If not, I'd be happy to give it try.

**Comment by SergeStinckwich** [comment]
No. Go ahead :-)
