### ISSUE TITLE
`(1e10 - 1e-10i) sqrt` does not work

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/PolyMath#221]
I try to compute: ``(1e10 - 1e-10i) sqrt`` and I got a division by zero error.

I'm wondering if this is not the same bug than in Math.js: https://github.com/josdejong/mathjs/pull/208
Any comments on that @nicolas-cellier-aka-nice ?

**Comment by olekscode** [comment]
The problem comes from `PMComplex >> abs` and it can be described like this:
```st
superBig := 1e10 * 1e10.
superSmall := 1e-10 * 1e-10.

superSmall = 0. "false"

superBig + superSmall = superBig. "true"
superBig - superSmall = superBig. "true"
```

I think this is an awesome bug 😃

**Comment by olekscode** [comment]
Which is why in this method:
```st
sqrt
	"Return the square root of the receiver with a positive imaginary part."

	| u v |
	(imaginary = 0 and: [real >= 0])
		ifTrue:	[^self class real: real sqrt imaginary: 0].
	v := (self abs - real / 2) sqrt.
	u := imaginary / 2 / v.
	^self class real: u imaginary: v
```
when we check if `imaginary = 0`, the answer is `false`
But inside `PMComplex >> abs` this happens:
```st
abs
	"Answer the distance of the receiver from zero (0 + 0 i)."

	^ ((real * real) + (imaginary * imaginary)) sqrt
```
So `superBig + superSmall = superBig`
And therefore `self.abs = real`
And `self.abs - real = 0`

Hence a zero divide

**Comment by olekscode** [comment]
I have opened an issue in Pharo: https://github.com/pharo-project/pharo/issues/11152
We will discuss it there and if it is possible to fix it, the problem will be gone.
Otherwise, we will adapt the PolyMath code to deal with this issue

**Comment by nicolas-cellier-aka-nice** [comment]
Good find, implementation of Complex sqrt is too naive.
