### ISSUE TITLE
Move all methods and tests related to complex numbers from PMMatrix and PMVector into Math-Complex package

### ISSUE THREAD

**Issue by olekscode** [PolyMathOrg/PolyMath#275]
This would remove the coupling between Collections and Complex numbers (which live in a separate package).

Some (perhaps not all) examples include:

- PMVector >> isReal
- PMMatrix >> isReal
- PMVectorTest >> testIsRealOnComplexVector
- PMVectorTest >> testIsRealOnRealVector
- PMMatrixTest >> testIsRealOnComplexMatrix
- PMMatrixTest >> testIsRealOnRealMatrix

Those methods can apply both to real and complex matrices. But implementation depends on PMComplex, so I don't know what to do there:

- PMMatrix >> isHermitian
- PMMatrix >> isNegativeDefinite
- PMMatrix >> isNegativeSemiDefinite
- PMMatrix >> isPositiveDefinite
- PMMatrix >> isPositiveSemiDefinite

**Comment by hemalvarambhia** [comment]
One thing worth noting is that matrices are defined over **Fields** (set and the binary operation +, *). Perhaps that is the worth exploring in answer to the messages `isHermitian` etc.

**Comment by jecisc** [comment]
First step in: https://github.com/PolyMathOrg/PolyMath/pull/292
