### ISSUE TITLE
PMVector/PMMatrix >> #dot: does not compute a dot product.

### ISSUE THREAD

**Issue by emdonahue** [PolyMathOrg/PolyMath#29]
Currently, #* computes the dot product:
#(1 2) asPMVector * #(2 1) asPMVector. "4"

and #dot: computes elementwise multiplication:
#(1 2) asPMVector dot: #(2 1) asPMVector.  "a PMVector(2 2)"

#dot: should probably be renamed to something like #elementwiseMultiply: or maybe a shorter binary message.

**Comment by olekscode** [comment]
I think I could swap them.
But wouldn't it silently break all the code that has ever used this multiplication?

**Comment by apocalypsemystic** [comment]
Yes, for that reason I think swap is a bad idea. Still, having #dot: not compute the dot product is probably not ideal under any circumstances. My thought would be to leave the default multiplication #* as the dot product, make #dot: just delegate to #*, and add a new method for elementwise multiplication.

**Comment by SergeStinckwich** [comment]
We can try to swap because I don't silent breaks ;-) we have also a lot of tests to cover these kind of changes. Before that we can have a look to dot: implementors if they are any others.

**Comment by apocalypsemystic** [comment]
I don't think we should swap. I didn't fully think it through before I made that suggestion. Dot product IS the default multiplication for matrices and vectors, so it makes sense to leave #* as the dot product. I think all we need to do is rename #dot: to something like #elementwiseMultiply: or maybe some shorter binary message.

**Comment by nicolas-cellier-aka-nice** [comment]
Indeed, dot: is misleading and should be renamed...
But I never saw * used for dot product elsewhere. Usually it can be array product (element-wise), or matrix product (matrix*vector), or external product in a space vector (scalar*vector).
If * is both dot product and scalar product, then (u*v)*w ~= u*(v*w)

**Comment by hemalvarambhia** [comment]
I had a quick look at wikipedia and this binary operation is referred to as the Hadamard product (or Schur product/entrywise product) and the symbol used to refer to it is a circle with a dot inside it. Could we call the message `circleDot` instead of `dot`?

**Comment by SergeStinckwich** [comment]
yes better to be more precise. Maybe ``hadamardProduct`` ?

**Comment by hemalvarambhia** [comment]
I think we can introduce `hadamardProduct` as you say and deprecate the `dot` message, after your mentioning your concern about silent breaks.
