### ISSUE TITLE
Fix SMark fails when trying to load PolyMath in Pharo 7.0

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/PolyMath#56]
When trying to port PolyMath to Pharo 7.0, I find that SMark fails in Pharo 7.0 : https://travis-ci.org/PolyMathOrg/PolyMath/jobs/397973698

```ScriptStarter class>>install``` use ```#ifNotNilDo:``` that is deprecated since Pharo 6.1. The problem has been reported upstream to Max Leske.

**Comment by theseion** [comment]
SMark now has a new stable version 1.0.2, which is also **marked** as stable (meaning, you can use `#stable` as version description).

Version 1.0.2 includes a couple of minor compatibility improvements and pulls in an updated version of the Scripting package, in which I have replaced the use of `#ifNotNilDo:`.

Let me know if I broke something.
