### ISSUE TITLE
Rename packages that have DHB in their names

### ISSUE THREAD

**Issue by olekscode** [PolyMathOrg/PolyMath#62]
The following packages still have the DHB part in their names:
* ```Math-DHB-Numerical```
* ```Math-Tests-DHB-Numerical```
* ```Math-Tests-DHB-wk```

We should change DHB to PM.
However (!), it would be much better to come up with better names for these packages. At this moment the naming is very inconsistent. For example, the tests for `PMMatrix` are in package `Math-Tests-Matrix` and the tests for `PMVector` are in `Math-Tests-DHB-Numerical`.

**Comment by SergeStinckwich** [comment]
Or remove completely PM or DHB, because they have all a Math prefix.

**Comment by olekscode** [comment]
Is Math a good prefix?
We will be prefixing all classes with PM, so maybe we can use the same prefix for packages?

Of course, `PM-Tests` doesn't look as good as `Math-Tests`, but two different prefixes may confuse the users.

**Comment by olekscode** [comment]
I propose creating a file where we describe the style rules (brief style guide).
Then we can post the link to in on the mailing list and Discord and discuss with everyone what could be the best naming conventions.

This way we should redefine all names in PolyMath and make them consistent with each other.

For example:
**Packages:** PM-{Package}-{Name}
**Classes:** PM{ClassName}
**Test packages:** PM-Tests-{Name}
**Test classes:** PM{Name}Test

Another big question is what should be the level of abstraction. Right now we have many packages which have just one class inside (especially test packages), and other packages that have so many classes that they could be split into different packages.

I think it's a very difficult question, but probably we should start by defining the whole scope of applications of PolyMath. For example, _"PolyMath is a library of numerical algorithms"_. Then split this area into subareas. Example: _"Statistics", "Linear algebra", "Machine Learning"_, etc. (we can use the chapters of Numerical Methods book as a reference, but we need to update this classification because modern PolyMath is different from what it was back then). Then each group could be a package: `PM-Statistics`, `PM-Linear-Algebra`, `PM-Machine-Learning`. And then: `PM-Tests-Statistics`, `PM-Tests-Linear-Algebra`, `PM-Tests-Machine-Learning`.

This is just an idea. I think that we need to discuss this with everyone and make a style guide.

**Comment by SergeStinckwich** [comment]
I agree mostly with what you say, but I'm a reluctant to move all ```Math-XXX package``` to ```PM-XXX```. First of all because it will need a lot of changes and then because if look at current packages names, most of the time there is not acronyms in package names. So for the moment, until we release 1.0, we can keep ```Math-XXX``` or rename with ```PolyMath-XXX```.

**Comment by SergeStinckwich** [comment]
yes the whole scope of PolyMath is a library of numerical algorithms and then we need to split in different meaningfull packages : ```PolyMath-Algebra```, ```PolyMath-DataAnalysis```, etc ...

**Comment by SergeStinckwich** [comment]
There is no more package with DHB inside. What is only missing is classes without PM prefix.

**Comment by hemalvarambhia** [comment]
@SergeStinckwich I'll get on to that.
