### ISSUE TITLE
Class PMVector overrides `==`

### ISSUE THREAD

**Issue by khinsen** [PolyMathOrg/PolyMath#90]
`PMVector` is the only class in my Pharo image that overrides `ProtoObject >> ==`, whose comment clearly states that no class should ever override it.

**Comment by SergeStinckwich** [comment]
This is part of DHB original code that was copy-paste in PolyMath, so maybe we have to remove it.

**Comment by AtharvaKhare** [comment]
My understanding is that `==` method checks if both arguments refer to the same object (both have same object pointer). In `PMVector ==`, it is comparing every element of the vector. Is this correct?

I think renaming the it to `isEqualTo` or something similar would be better?

**Comment by AtharvaKhare** [comment]
My understanding is that `==` is used to check if two objects pointers refer to the same location (both objects are same) and it is already defined in `ProtoObject`, there is no reason to override it.

The way `PMVector ==` is implemented, it is checking for equality of contents of the objects, and not the objects itself (or memory location of them).

Better would be renaming it to something like `isEqualTo:`.

Am I correct?

**Comment by AtharvaKhare** [comment]
My understanding is that `==` is used to check if two objects pointers refer to the same location (both objects are same) and it is already defined in `ProtoObject`, there is no reason to override it.

The way `PMVector ==` is implemented, it compares the contents of the object and not the memory location. Renaming it to something like `isEqualTo` (or `=`?) would be better.

Am I correct?

**Comment by AtharvaKhare** [comment]
My understanding is that `==` is used to check if two objects pointers refer to the same location (both objects are same) and it is already defined in `ProtoObject`, there is no reason to override it.

The way `PMVector ==` is implemented, it compares the contents of the object and not the memory location. Renaming it to something like `isEqualTo` (or `=`?) would be better.

Am I correct?

**Comment by khinsen** [comment]
@AtharvaKhare Your analysis is correct, but I'd go farther in the conclusion: overriding `==` is not only useless but potentially dangerous because it breaks the semantics of the operation.

You suggest renaming it, but do you actually see any situation in which it might be useful? Note that `=` is already there (inherited from `SequenceableCollection`), but does something different from `PMVector>>==`.

**Comment by AtharvaKhare** [comment]
@khinsen right, I get it :)

Also, looking at the comment and the syntax `== aNumber`, I think it is intended to apply `==` to every element of the vector, so it is not the same as `=`, which tests for equal contents between objects.
So I think it's use is like this (when rename to something like `isEqualTo`:
```
x := #(1 1 1) asPMVector.
x isEqualToThis: 1
>>> a PMVector(false false false)
```

I also have a question about the API, why do these arithmetic operators (`>`, `<`, `isEqualTo`) modify the object and not return a new one, whereas `+`, `-`, `*` return new one?

**Comment by SergeStinckwich** [comment]
Do you understand what is == ? why classes should not reimplement it ?

**Comment by khinsen** [comment]
My question was rather if you see a situation where one might actually want to use it.  Why would I ever want to know if all elements of a vector are one-by-one identical? I don't see a good use case, but obviously the author of that code did, so maybe I am just missing it.

**Comment by AtharvaKhare** [comment]
I can't figure out how it would be useful for PMVector, but in Dataseries, it can be used for converting binary categories to 0-1s.

**Comment by khinsen** [comment]
Element-by-element comparison yielding a vector/series of booleans are definitely useful in some circumstances. What I don't see is the utility of testing for element-wise object identity. Identity tests a (`==`) are rarely used. In Pharo I mostly see them as a first step in equality tests, to avoid doing more expensive comparisons. That scenario never happens for elementwise comparison of vectors. So what would be a situation where elementwise identity matters?

**Comment by AtharvaKhare** [comment]
I got a bit confused between `==` and `=` in my previous reply. I can't think of any application that would need `==`.

**Comment by SergeStinckwich** [comment]
`==` is used everytime you need to be sure objects are unique, for example in a Set. Look at `==` senders in your image. There are more than 9000 in my image, so this is used a lot of time actually :-)

**Comment by khinsen** [comment]
`Set` uses `=` for comparing elements, it's `IdentitySet` that uses `==`.

I was a bit surprised by the 9000 senders, so I decided to look at them myself. It's even 12000 in my image, but most of the methods found don't actually use `==`. What they do contain instead is `ifNil:` and/or `ifNotNil:`. Perhaps the compiler replaces those by `== nil`. Anyway, I have no idea how to find the real uses of `==`. A text search in all methods also finds `==>`, comments, etc.
