### ISSUE TITLE
add support for diagonal function?

### ISSUE THREAD

**Issue by fuhrmanator** [PolyMathOrg/PolyMath#91]
I'm doing some software history (co-change) calculations with matrices using PolyMath and I need to get the ~~`diagonal`~~ `principalDiagonal` of a (~~symmetric~~ square) `PMMatrix` to see total changes for each software class. 

I did not find an obvious way to do this, so I'm probably going to write it as an extension. Is this something you want to have as a pull request? Also, perhaps I missed the obvious?

**Comment by SergeStinckwich** [comment]
I dunno how it happens, but there was a missing ] in your commit : https://github.com/PolyMathOrg/PolyMath/commit/3e8d1eecc0453328db408afa5473927d5928f99d#diff-ae5284ffc9b9802fb493ca318d25b044 
You edit the file by hand ?

Your commit was push to dev branch. Thank you.

**Comment by fuhrmanator** [comment]
My edit by hand of what I thought was just a single file caused a huge
change that I don't understand. Can you check this? The ] appears to have
been lost in this merge. I think what happened was I hand edited a file on
a different branch? I am very sorry and won't try that ever again!

https://github.com/PolyMathOrg/PolyMath/commit/3db369c8e5409d0973c7954dd7bff066ea67a4e4

**Comment by SergeStinckwich** [comment]
Ok there is no problem, Christopher :-) We should be more vigilant when we accept PR and avoid as much as possible to edit by hand. Next time I will spend more time looking at the CI.
