### ISSUE TITLE
Some tests are not run

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/PolyMath#99]
Normally there are 767 tests but only 743 are run on the CI: https://travis-ci.org/PolyMathOrg/PolyMath/jobs/523852121

**Comment by SergeStinckwich** [comment]
Apparently I fix this issue inadvertently :-) We have 797 green tests in image and CI.

**Comment by hemalvarambhia** [comment]
Well done! In that case let's close..
